### PR TITLE
discard preamble after lexing

### PR DESCRIPTION
**Pull request by PratikDeoghare**
Also added a basic test.

It can be run with `python3 -m unittest discover`. 

PTAL. Thanks!

### CODE REVIEW

**Comment by PratikDeoghare** [comment]
Hmm the TLA+ parser also parses the following. 

Which means this PR is does not solve the problem completely. 😬 

```
---- What is this 

\* A comment 

And more preamble there is.

------------------------------- MODULE Somename -------------------------------
```

**Comment by PratikDeoghare** [comment]
TLA+ parser errors on this input. A bug? 

```
---- What is this 

\* A comment 
\* ---- MODULE foo ----
And more preamble there is.

------------------------------- MODULE Foo -------------------------------


=============================================================================
``` 

image

**Comment by PratikDeoghare** [comment]
Made it match the module definition here https://lamport.azurewebsites.net/tla/TLAPlus2Grammar.tla

**Comment by PratikDeoghare** [comment]
@lemmy This is ready for review. Ptal. Thanks!

**Comment by lemmy** [comment]
Do you know what happens if there is text in the footer (after the TLA+ module end marker)?

**Comment by lemmy** [comment]
Thanks: https://github.com/tlaplus/PlusPy/commit/46a566d8953ab6dff18e7e16f3cea933c3aa1489

**Comment by PratikDeoghare** [comment]
>  Do you know what happens if there is text in the footer (after the TLA+ module end marker)?

If there are comments in the footer, they never go beyond the lexer. 

If there is anything else then it's put in a`Remainder`.  See below the lexer output has `FooTwo` but the AST doesn't. 

When parser sees `====` it knows that the module has ended. See [here](https://github.com/tlaplus/PlusPy/blob/46a566d8953ab6dff18e7e16f3cea933c3aa1489/pluspy.py#L811). I doesn't handle multiple modules in single file. 

`foo.tla`

```

\* No tokens for this

---- MODULE Foo -----

====


\* Footer and a module beyond

Something else

---- MODULE FooTwo -----

====

Another footer
```

Output from Lexer

`[('----', ('./tests/foo.tla', 4), 1, True), ('MODULE', ('./tests/foo.tla', 4), 6, False), ('Foo', ('./tests/foo.tla', 4), 13, False), ('----', ('./tests/foo.tla', 4), 17, False), ('====', ('./tests/foo.tla', 6), 1, True), ('Something', ('./tests/foo.tla', 11), 1, True), ('else', ('./tests/foo.tla', 11), 11, False), ('----', ('./tests/foo.tla', 13), 1, True), ('MODULE', ('./tests/foo.tla', 13), 6, False), ('FooTwo', ('./tests/foo.tla', 13), 13, False), ('----', ('./tests/foo.tla', 13), 20, False), ('====', ('./tests/foo.tla', 15), 1, True), ('Another', ('./tests/foo.tla', 17), 1, True), ('footer', ('./tests/foo.tla', 17), 9, False)]`


AST: 
```
(GModule,
.[
..(Name, '('Foo', ('./tests/foo.tla', 4), 13, False)')
..(Optional, None)
..(AtLeast0,
...[
...]
..)
.]
)
Remainder ('Something', ('./tests/foo.tla', 11), 1, True)
```

**Pull request closed without merging**
